### ISSUE TITLE
upload pictures here

### ISSUE THREAD

**Issue by shawaj** [PiSupply/StakeBox-PaPiRus#1]

**Comment by shawaj** [comment]
<img width="800" alt="stakebox-wide-black 2x" src="https://user-images.githubusercontent.com/3359418/41306328-b152a996-6e6d-11e8-974a-14488860586d.png">

**Comment by shawaj** [comment]
![ppr](https://user-images.githubusercontent.com/3359418/41306365-d4aa3828-6e6d-11e8-87ad-79516298ea81.png)

**Comment by ChristopherRush** [comment]
![stakebox-github-banner](https://user-images.githubusercontent.com/1878314/73882515-1f715900-485a-11ea-8144-e7dbc0e4683b.png)
